# Generated by Django 6.0.2 on 2026-03-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='scanreport',
            name='drawing_image',
            field=models.ImageField(blank=True, null=True, upload_to='drawings/'),
        ),
        migrations.AddField(
            model_name='scanreport',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanreport',
            name='scan_image',
            field=models.ImageField(blank=True, null=True, upload_to='scans/'),
        ),
        migrations.AlterField(
            model_name='scanreport',
            name='scan_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
