# Generated by Django 6.0.2 on 2026-03-03 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_appointment_reason_doctorprofile_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='BladSense AI', max_length=100)),
                ('version', models.CharField(default='2.1.0', max_length=50)),
                ('build_number', models.CharField(default='402', max_length=50)),
                ('description', models.TextField()),
                ('footer_text', models.CharField(default='Made with ❤ by BladSense Team', max_length=255)),
                ('copyright_text', models.CharField(default='© 2024 BladSense Inc. All rights reserved.', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('icon_type', models.CharField(max_length=50)),
                ('app_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='doctor.appinfo')),
            ],
        ),
    ]
