# Generated by Django 6.0.2 on 2026-03-03 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_appinfo_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_scans', models.IntegerField(default=0)),
                ('scans_increase_pct', models.FloatField(default=0.0)),
                ('avg_volume', models.CharField(default='0ml', max_length=50)),
                ('volume_decrease_pct', models.FloatField(default=0.0)),
                ('active_patients', models.IntegerField(default=0)),
                ('patients_increase', models.IntegerField(default=0)),
                ('retention_rate', models.FloatField(default=0.0)),
                ('retention_increase_pct', models.FloatField(default=0.0)),
                ('trend_monday', models.FloatField(default=0.0)),
                ('trend_tuesday', models.FloatField(default=0.0)),
                ('trend_wednesday', models.FloatField(default=0.0)),
                ('trend_thursday', models.FloatField(default=0.0)),
                ('trend_friday', models.FloatField(default=0.0)),
                ('trend_saturday', models.FloatField(default=0.0)),
                ('trend_sunday', models.FloatField(default=0.0)),
                ('scan_duration_seconds', models.FloatField(default=0.0)),
                ('image_quality_pct', models.FloatField(default=0.0)),
                ('report_gen_seconds', models.FloatField(default=0.0)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='doctor.doctorprofile')),
            ],
        ),
    ]
