# Generated by Django 6.0.2 on 2026-03-03 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_analyticsdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='temp_scans/')),
                ('quality_score', models.FloatField(default=0.0)),
                ('quality_label', models.CharField(max_length=50)),
                ('feedback_message', models.TextField()),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctorprofile')),
            ],
        ),
    ]
