# Generated by Django 6.0.2 on 2026-03-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_scanvalidation'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(default='Initial Scan', max_length=100),
        ),
    ]
