# Generated by Django 6.0.2 on 2026-03-03 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_appointment_duration_minutes_appointment_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.CharField(max_length=50)),
                ('item_count', models.IntegerField()),
                ('backup_file', models.FileField(blank=True, null=True, upload_to='backups/')),
                ('status', models.CharField(default='Success', max_length=50)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='doctor.doctorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_backup', models.BooleanField(default=True)),
                ('include_images', models.BooleanField(default=True)),
                ('wifi_only', models.BooleanField(default=True)),
                ('last_backup_at', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='backup_settings', to='doctor.doctorprofile')),
            ],
        ),
    ]
