# Generated by Django 6.0.2 on 2026-03-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_backup_backupsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanvalidation',
            name='view_type',
            field=models.CharField(default='transverse', max_length=50),
        ),
    ]
