# Generated by Django 6.0.2 on 2026-03-03 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_supportmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessibilitySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_guidance', models.BooleanField(default=False)),
                ('screen_reader_optimized', models.BooleanField(default=False)),
                ('high_contrast', models.BooleanField(default=False)),
                ('button_size', models.CharField(default='Medium', max_length=20)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accessibility_settings', to='doctor.doctorprofile')),
            ],
        ),
    ]
