# Generated by Django 6.0.2 on 2026-03-03 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0011_accessibilitysettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplaySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(default='Light', max_length=20)),
                ('volume_units', models.CharField(default='Milliliters (ml)', max_length=50)),
                ('language', models.CharField(default='English', max_length=50)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='display_settings', to='doctor.doctorprofile')),
            ],
        ),
    ]
