# Generated by Django 6.0.2 on 2026-03-03 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0012_displaysettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Probe C5-2', max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(default='Connected', max_length=20)),
                ('battery_level', models.IntegerField(default=100)),
                ('temperature', models.IntegerField(default=35)),
                ('signal_strength', models.CharField(default='5GHz', max_length=20)),
                ('last_calibration', models.DateTimeField(blank=True, null=True)),
                ('next_service_due', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='doctor.doctorprofile')),
            ],
        ),
    ]
