# Generated by Django 6.0.2 on 2026-03-03 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0014_estimationresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.CharField(blank=True, max_length=50, null=True)),
                ('categories_included', models.IntegerField(default=4)),
                ('download_url', models.URLField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='doctor.doctorprofile')),
            ],
        ),
    ]
