# Generated by Django 6.0.2 on 2026-03-04 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0019_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('last_updated', models.DateField(auto_now=True)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
            ],
        ),
    ]
