# Generated by Django 6.0.3 on 2026-03-09 04:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0021_recommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('video_url', models.URLField(blank=True, null=True)),
                ('takeaways', models.JSONField(default=list)),
                ('duration_minutes', models.IntegerField(default=15)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='biometric_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='last_password_change',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='location',
            field=models.CharField(default='Building A, Floor 3', max_length=255),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='technician_level',
            field=models.CharField(default='Level 1', max_length=50),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='two_factor_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='years_of_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TeamInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('fullName', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=100)),
                ('licenseNumber', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to='doctor.doctorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=255)),
                ('staff_id', models.CharField(max_length=50, unique=True)),
                ('role', models.CharField(max_length=100)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('years_of_experience', models.IntegerField(default=0)),
                ('total_scans', models.IntegerField(default=0)),
                ('accuracy_pct', models.IntegerField(default=0)),
                ('total_patients', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='doctor.doctorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('is_current', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='doctor.doctorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_progress', to='doctor.doctorprofile')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='doctor.trainingmodule')),
            ],
            options={
                'unique_together': {('doctor', 'module')},
            },
        ),
    ]
