# Generated by Django 6.0.3 on 2026-03-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0022_trainingmodule_doctorprofile_biometric_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
