# Generated by Django 6.0.3 on 2026-03-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0023_patient_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='condition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
